import yfinance as yf

STOCKS = [
"DEEPAKNTR","NIACL","IRB","SYNGENE","IGL","TATATECH","GUJGASLTD","AWL","SONACOMS","KPRMILL",
"EXIDEIND","APARINDS","SJVN","LICHSGFIN","MEDANTA","HONAUT","KPITTECH","ACC","TATAINVEST",
"APOLLOTYRE","GODFRYPHLP","JUBLFOOD","AJANTPHARM","TATAELXSI","CRISIL","ENDURANCE","THERMAX",
"AIAENG","NLCINDIA","FLUOROCHEM","BLUESTARCO","UCOBANK","IREDA","PAGEIND","ASTRAL","ITCHOTELS",
"IPCALAB","COCHINSHIP","CONCOR","GLAXO","UBL","ESCORTS","PGHH","KEI","LTTS","PETRONET","HUDCO",
"DALBHARAT","SUPREMEIND","VOLTAS","JKCEMENT","KALYANKJIL","BALKRISIND","PIIND","MOTILALOFS",
"M&MFIN","TATACOMM","IRCTC","MAHABANK","LINDEINDIA","GODREJPROP","APLAPOLLO","MPHASIS",
"NAM_INDIA","GLENMARK","OBEROIRLTY","SUNDARMFIN","MFSL","SCHAEFFLER","COFORGE","COLPAL",
"ABBOTINDIA","ATGL","BIOCON","BERGEPAINT","SAIL","MRF","UPL","PRESTIGE","JSL","SUZLON",
"PHOENIXLTD","GICRE","UNOMINDA","FORTIS","DIXON","NATIONALUM","AUROPHARMA","FEDERALBNK",
"BHARATFORG","TORNTPOWER","RVNL","IOB","COROMANDEL","YESBANK","OFSS","ALKEM","NMDC","NYKAA",
"OIL","INDUSINDBK","IDFCFIRSTB","BANKINDIA","AUBANK","SBICARD","NHPC","PAYTM","JSWENERGY",
"HAVELLS","NAUKRI","SRF","BHEL","MANKIND","ZYDUSLIFE","DABUR","CGPOWER","INDHOTEL","ICICIGI",
"ABCAPITAL","HINDPETRO","MAZDOCK","ICICIPRULI","RECLTD","UNITDSPR","MAXHEALTH","DRREDDY",
"LODHA","MARICO","SHREECEM","LUPIN","APOLLOHOSP","ABB","PERSISTENT","GMRAIRPORT","SIEMENS",
"IDBI","BOSCHLTD","GAIL","JINDALSTEL","ASHOKLEY","ADANIPOWER","POLYCAB","BSE","HDFCAMC",
"INDUSTOWER","IDEA","CUMMINSIND","CIPLA","HEROMOTOCO","TATAPOWER","MOTHERSON","SOLARINDS",
"INDIANB","TATACONSUM","BAJAJHLDNG","PFC","GODREJCP","AMBUJACEM","UNIONBANK","TORNTPHARM",
"TRENT","CHOLAFIN","CANBK","BRITANNIA","PNB","ADANIGREEN","PIDILITIND","DLF","IRFC","BPCL",
"BANKBARODA","MUTHOOTFIN","HDFCLIFE","DIVISLAB","TECHM","VBL","JIOFIN","TVSMOTOR","LTIM",
"GRASIM","INDIGO","SHRIRAMFIN","EICHERMOT","SBILIFE","HINDALCO","IOC","TATASTEEL",
"POWERGRID","DMART","NESTLEIND","WIPRO","COALINDIA","BAJAJ_AUTO","ASIANPAINT","VEDL",
"ADANIENT","JSWSTEEL","HAL","ADANIPORTS","BEL","ONGC","BAJAJFINSV","NTPC","ULTRACEMCO",
"TITAN","SUNPHARMA","AXISBANK","ITC","KOTAKBANK","M&M","HCLTECH","MARUTI","LICI","LT",
"HINDUNILVR","BAJFINANCE","INFY","SBIN","ICICIBANK","TCS","BHARTIARTL","HDFCBANK","RELIANCE"
]

def fetch_stocks():
    results = []

    for s in STOCKS:
        sym = f"{s}.NS"
        try:
            t = yf.Ticker(sym)
            info = t.fast_info

            last = info.get("lastPrice")
            prev = info.get("previousClose")

            if not last or not prev:
                continue

            change = ((last - prev) / prev) * 100

            results.append({
                "id": f"STOCK:{s}",
                "price": float(last),
                "change": float(change)
            })

        except Exception as e:
            print(f"Stock failed {s}: {e}")

    return results
