name: ETF & Stock Tracker (Persistent)

on:
  schedule:
    # Every 15 min during Indian market hours (IST → UTC)
    - cron: '45,0,15,30 3-9 * * 1-5'
    # Guaranteed EOD run (15:31 IST)
    - cron: '1 10 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml yfinance pytz

      - name: Download state
        uses: actions/download-artifact@v4
        with:
          name: state
          path: state
        continue-on-error: true

      - name: Run tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tracker.py

      - name: Upload state
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state
