name: ETF & Stock Tracker

on:
  schedule:
    # Market hours: 9:15 AM - 3:15 PM IST = 3:45 AM - 9:45 AM UTC
    # Runs every 15 minutes during market hours, Monday to Friday
    - cron: '15,30,45 3-9 * * 1-5'
    
    # Daily summary at 3:30 PM IST = 10:00 AM UTC
    - cron: '0 10 * * 1-5'
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  track-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run ETF & Stock Tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MONGO_URL: "mongodb://localhost:27017"
          DB_NAME: "etf_tracker"
        run: |
          python standalone_tracker.py
